//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CContact, CMessageWrap, NSMutableArray;

@interface BrandSingleMsgCellViewModel : NSObject
{
    _Bool _hasBottomLine;
    CMessageWrap *_messageWrap;
    CContact *_brandContact;
    NSMutableArray *_messageLabelStyles;
    NSMutableArray *_contactLabelStyles;
    NSMutableArray *_timeLabelStyles;
    double _viewHeight;
    struct CGSize _messageLabelSize;
    struct CGSize _contactLabelSize;
    struct CGSize _timeLabelSize;
}

+ (id)cellResueIdentifier;
@property(nonatomic) double viewHeight; // @synthesize viewHeight=_viewHeight;
@property(nonatomic) struct CGSize timeLabelSize; // @synthesize timeLabelSize=_timeLabelSize;
@property(retain, nonatomic) NSMutableArray *timeLabelStyles; // @synthesize timeLabelStyles=_timeLabelStyles;
@property(nonatomic) struct CGSize contactLabelSize; // @synthesize contactLabelSize=_contactLabelSize;
@property(retain, nonatomic) NSMutableArray *contactLabelStyles; // @synthesize contactLabelStyles=_contactLabelStyles;
@property(nonatomic) struct CGSize messageLabelSize; // @synthesize messageLabelSize=_messageLabelSize;
@property(retain, nonatomic) NSMutableArray *messageLabelStyles; // @synthesize messageLabelStyles=_messageLabelStyles;
@property(retain, nonatomic) CContact *brandContact; // @synthesize brandContact=_brandContact;
@property(nonatomic) _Bool hasBottomLine; // @synthesize hasBottomLine=_hasBottomLine;
@property(retain, nonatomic) CMessageWrap *messageWrap; // @synthesize messageWrap=_messageWrap;
- (void).cxx_destruct;
- (id)makeEmoticonMessageText:(id)arg1;
- (id)textForMsgLabelWithSender:(id)arg1 messageWrap:(id)arg2;
- (id)messageTextForShow;
- (id)cellIdentifier;
- (id)initWithMessage:(id)arg1;

@end

