//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BrandTimelineBaseCellView, CContact, CMessageWrap, MMUIViewController, UIView;

@protocol BrandTimelineBaseCellViewDelegate <NSObject>

@optional
- (MMUIViewController *)getViewController;
- (void)onPreviewMsgImg:(CMessageWrap *)arg1 originFrame:(struct CGRect)arg2 fromView:(UIView *)arg3;
- (void)onLongPressForDebug:(CMessageWrap *)arg1;
- (void)reloadCellWithCellView:(BrandTimelineBaseCellView *)arg1;
- (void)onDeleteBrandContact:(CContact *)arg1;
- (void)onCellViewClickedExpan:(BrandTimelineBaseCellView *)arg1;
@end

