//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CContact, CMessageWrap, NSMutableArray, NSString;

@interface BrandTimelineBaseViewModel : NSObject
{
    _Bool _isLastNewMsg;
    _Bool _bHasLastMsgSeparateLine;
    unsigned int _sectionIndex;
    CMessageWrap *_messageWrap;
    unsigned long long _showType;
    CContact *_brandContact;
    NSMutableArray *_contactLabelStyles;
    NSMutableArray *_timeLabelStyles;
    NSString *_displayTimeStr;
    struct CGSize _viewSize;
    struct CGSize _contactLabelSize;
    struct CGSize _timeLabelSize;
}

+ (_Bool)canCreateViewModelWithMessage:(id)arg1 ShowType:(unsigned long long)arg2;
+ (id)createModelWithMessage:(id)arg1 ShowType:(unsigned long long)arg2;
+ (id)createModelWithMessage:(id)arg1;
@property(retain, nonatomic) NSString *displayTimeStr; // @synthesize displayTimeStr=_displayTimeStr;
@property(nonatomic) struct CGSize timeLabelSize; // @synthesize timeLabelSize=_timeLabelSize;
@property(retain, nonatomic) NSMutableArray *timeLabelStyles; // @synthesize timeLabelStyles=_timeLabelStyles;
@property(nonatomic) struct CGSize contactLabelSize; // @synthesize contactLabelSize=_contactLabelSize;
@property(retain, nonatomic) NSMutableArray *contactLabelStyles; // @synthesize contactLabelStyles=_contactLabelStyles;
@property(retain, nonatomic) CContact *brandContact; // @synthesize brandContact=_brandContact;
@property(nonatomic) unsigned long long showType; // @synthesize showType=_showType;
@property(nonatomic) _Bool bHasLastMsgSeparateLine; // @synthesize bHasLastMsgSeparateLine=_bHasLastMsgSeparateLine;
@property(readonly, nonatomic) struct CGSize viewSize; // @synthesize viewSize=_viewSize;
@property(retain, nonatomic) CMessageWrap *messageWrap; // @synthesize messageWrap=_messageWrap;
@property(nonatomic) _Bool isLastNewMsg; // @synthesize isLastNewMsg=_isLastNewMsg;
@property(nonatomic) unsigned int sectionIndex; // @synthesize sectionIndex=_sectionIndex;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool bIsTopContact;
@property(readonly, nonatomic) _Bool bIsExpand;
@property(readonly, nonatomic) double containerViewHeight;
@property(readonly, nonatomic) double viewHeight;
- (id)displayTime;
@property(readonly, nonatomic) unsigned long long sequenceId;
- (id)cellIdentifier;
- (id)createBrandTimelineBaseCellView;
- (id)cellViewClassName;
- (id)initWithMessage:(id)arg1 ShowType:(unsigned long long)arg2;

@end

