//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MemoryMappedKV, WCTDatabase, WCTTable;

@interface BrandTimelineMsgDB : NSObject
{
    WCTDatabase *m_db;
    WCTTable *m_tableTimeline;
    WCTTable *m_tableTimelineSingleMsg;
    MemoryMappedKV *_mappedKV;
}

@property(retain, nonatomic) MemoryMappedKV *mappedKV; // @synthesize mappedKV=_mappedKV;
- (void).cxx_destruct;
- (id)setupTableWithName:(id)arg1 tableClass:(Class)arg2;
- (void)openTable;
- (void)clearDB;
- (void)close;
- (void)open;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1;
- (id)init;
- (void)dealloc;
- (id)convertSingleDBMsg2CMsgWrap:(id)arg1;
- (id)convertSingleDBMsgArr2CMsgWrapArr:(id)arg1;
- (id)convertTLDBMsg2CMsgWrap:(id)arg1;
- (id)convertTLDBMsgArr2CMsgWrapArr:(id)arg1;
- (void)clearAllSingleMsgUnreadStatus;
- (void)deleteUnreadSingleMsgWrapForSession:(id)arg1;
- (_Bool)insertSingleMsgWrap:(id)arg1;
- (id)getUnreadSingleMsgFromCreateTime:(unsigned int)arg1 limit:(unsigned int)arg2 leftCount:(unsigned int *)arg3;
- (unsigned int)getUnreadSingleMsgCountByUserName:(id)arg1;
- (unsigned int)getUnreadSingleMsgCount;
- (id)getLastUnreadSingleMsg;
- (void)deleteSession:(id)arg1;
- (void)deleteMsg:(id)arg1 msgWrap:(id)arg2;
- (_Bool)setMsgWrapExpand:(id)arg1;
- (void)clearAllMsgUnreadStatus;
- (_Bool)migrateMsgWrap:(id)arg1;
- (_Bool)insertMsgWrap:(id)arg1 isTopContact:(_Bool)arg2 createNewGroup:(_Bool)arg3;
- (void)resetGroupBaseTime;
- (unsigned int)getGroupBaseTime;
- (id)getMsgFromSequenceId:(unsigned long long)arg1 limit:(unsigned int)arg2 leftCount:(unsigned int *)arg3;
- (id)getLastMsg;
- (unsigned int)getUnreadTimelineMsgCount;

@end

