//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "WCActionSheetDelegate-Protocol.h"

@class BrandTimelineBaseViewModel, BrandTimelineHeaderContactBtn, NSString, UILabel;
@protocol BrandTimelineBaseHeaderViewDelegate;

@interface BrandTimelineBaseHeaderView : MMUIView <WCActionSheetDelegate>
{
    BrandTimelineHeaderContactBtn *_contactContentView;
    UILabel *_timeLabel;
    id <BrandTimelineBaseHeaderViewDelegate> _delegate;
    BrandTimelineBaseViewModel *_viewModel;
}

+ (double)viewHeight;
@property(nonatomic) __weak BrandTimelineBaseViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <BrandTimelineBaseHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)onShowCancelFocusTips:(id)arg1;
- (id)getAboutButtonTitle;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showActionSheet;
- (void)onLongPress:(id)arg1;
- (void)onClickContact:(id)arg1;
- (void)layoutSubviews;
- (void)initTimeLabel;
- (void)initContactView;
- (void)initSubviews;
- (void)updateTimeLabel;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

