//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "IMMNewSessionMgrExt-Protocol.h"
#import "IMsgExt-Protocol.h"
#import "INewABTestMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class ABTestItem, BrandTimelineMsgDB, MMBaseSessionStorage, MemoryMappedKV, NSString;

@interface BrandTimelineMsgMgr : MMService <IMsgExt, INewABTestMgrExt, IMMNewSessionMgrExt, MMService>
{
    _Bool _isMigratingData;
    MemoryMappedKV *_mappedKV;
    BrandTimelineMsgDB *_brandMsgDB;
    MMBaseSessionStorage *_sessionStorage;
    ABTestItem *_ABTestItemCache;
}

@property(retain, nonatomic) ABTestItem *ABTestItemCache; // @synthesize ABTestItemCache=_ABTestItemCache;
@property(nonatomic) _Bool isMigratingData; // @synthesize isMigratingData=_isMigratingData;
@property(retain, nonatomic) MMBaseSessionStorage *sessionStorage; // @synthesize sessionStorage=_sessionStorage;
@property(retain, nonatomic) BrandTimelineMsgDB *brandMsgDB; // @synthesize brandMsgDB=_brandMsgDB;
@property(retain, nonatomic) MemoryMappedKV *mappedKV; // @synthesize mappedKV=_mappedKV;
- (void).cxx_destruct;
- (void)onDeleteSessionOfUser:(id)arg1;
- (void)OnDelMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)onModifyABTestItem:(id)arg1 bizId:(id)arg2 abTestItem:(id)arg3;
- (_Bool)isBrandTimelineSchema5Open;
- (_Bool)isBrandTimelineOpen;
- (void)setUserChoice:(id)arg1;
- (id)getLastUserChoice;
- (_Bool)isABTestOpen;
- (void)checkIfNeedHandleMsg;
- (void)checkIfNeedMigrate;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (void)clearBrandTimelineData;
- (void)migrateBrandSessionAndMsg2Timeline;
- (_Bool)isFinishMigrateBrandMsg;
- (void)setMigrateFinishFlag:(_Bool)arg1;
- (void)OnUnReadCountChange:(id)arg1;
- (void)clearAllSingleMsgUnreadStatus;
- (void)deleteUnreadSingleMsgWrapForSession:(id)arg1;
- (id)getUnreadSingleMsgFromCreateTime:(unsigned int)arg1 limit:(unsigned int)arg2;
- (unsigned int)getUnreadSingleMsgCountByUserName:(id)arg1;
- (unsigned int)getUnreadSingleMsgCount;
- (id)getLastUnreadSingleMsg;
- (void)handleNewSingleMsg:(id)arg1;
- (void)handleNewMsgByTimeline:(id)arg1;
- (_Bool)isListMsgClearUnread;
- (void)setListMsgClearUnread:(_Bool)arg1;
- (unsigned long long)getDividingLineSequenceId;
- (void)setDividingLineSequenceId:(unsigned long long)arg1;
- (void)setTimelineMsgWrapExpand:(id)arg1;
- (void)deleteBrandMsg:(id)arg1 msgWrap:(id)arg2;
- (void)deleteBrandSession:(id)arg1;
- (id)getTimelineMsgFromSequenceId:(unsigned long long)arg1 limit:(unsigned int)arg2;
- (id)getLastTimelineMsg;
- (unsigned int)getUnreadTimelineMsgCount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

