//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "BrandTimelineMsgMgrExt-Protocol.h"
#import "MMRefreshTableFooterDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "tableViewDelegate-Protocol.h"

@class MMTableView, NSMutableArray, NSString, UIView, WCTimeLineFooterView;

@interface BrandSingleMsgListViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, tableViewDelegate, MMRefreshTableFooterDelegate, BrandTimelineMsgMgrExt>
{
    UIView *m_topNavView;
    MMTableView *m_tableView;
    WCTimeLineFooterView *m_footerView;
    NSMutableArray *m_arrViewModel;
    _Bool m_bLoadingData;
}

- (void).cxx_destruct;
- (void)onAddNewSingleMsg:(id)arg1;
- (void)updateLoadingState;
- (void)tryLoadDownMoreMessage;
- (_Bool)shouldDownMoreLoading;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onNavBackBarButtonClicked;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;
- (void)initNavigationBar;
- (void)initFooterView;
- (void)initTableView;
- (void)initView;
- (void)initData;
- (void)updateVisibleCellTime;
- (void)willEnterForeground:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

