//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BTLBaseItemViewModel.h"

#import "IAudioReceiverExt-Protocol.h"
#import "IMusicPlayerExt-Protocol.h"

@class MMMusicInfo, NSString;

@interface BTLAudioItemViewModel : BTLBaseItemViewModel <IAudioReceiverExt, IMusicPlayerExt>
{
    MMMusicInfo *m_musicInfo;
    _Bool _bPlaying;
}

+ (_Bool)canCreateViewModelWithReaderWrap:(id)arg1 msgWrap:(id)arg2;
@property(nonatomic) _Bool bPlaying; // @synthesize bPlaying=_bPlaying;
- (void).cxx_destruct;
- (void)onMusicPlayStatusChanged;
- (void)OnEndPlaying:(unsigned int)arg1 isForceStop:(_Bool)arg2;
- (void)OnBeginPlaying:(unsigned int)arg1 ErrNo:(int)arg2;
@property(readonly, nonatomic) MMMusicInfo *musicInfo;
- (id)coverImgURL;
@property(readonly, nonatomic) NSString *timeStr;
- (struct CGSize)titleSize;
- (id)titleStr;
- (id)titleLabelStyles;
- (double)viewHeight;
- (id)itemViewClassName;
- (id)initWithReaderWrap:(id)arg1 itemIndex:(unsigned int)arg2 msgWrap:(id)arg3 contact:(id)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

