//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BTLBaseItemView, MMUIViewController, UIView;

@protocol BTLBaseItemViewDelegate <NSObject>

@optional
- (void)onBrandItemImageClick:(BTLBaseItemView *)arg1 imageView:(UIView *)arg2;
- (void)onBrandItemFullTextBtnClick:(BTLBaseItemView *)arg1;
- (void)onBrandItemVoiceBtnClick:(BTLBaseItemView *)arg1;
- (void)onBrandItemLongPress:(BTLBaseItemView *)arg1;
- (void)onBrandItemClick:(BTLBaseItemView *)arg1;
- (void)onBrandItemTouchDown:(BTLBaseItemView *)arg1;
- (void)onReloadItemView:(BTLBaseItemView *)arg1;
- (MMUIViewController *)getViewController;
@end

