//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BTLBaseItemViewModel.h"

@class NSMutableArray;

@interface BTLReaderItemViewModel : BTLBaseItemViewModel
{
    NSMutableArray *m_digestLabelStyles;
    struct CGSize m_digestSize;
}

+ (_Bool)canCreateViewModelWithReaderWrap:(id)arg1 msgWrap:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGSize digestSize;
@property(readonly, nonatomic) NSMutableArray *digestLabelStyles;
- (struct CGSize)titleSize;
- (id)titleLabelStyles;
- (double)viewHeight;
- (id)itemViewClassName;

@end

