//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, QChinaBorder, QSpecialDistrictBorder;

@interface QBorderManager : NSObject
{
    int _version;
    NSString *_filePath;
    QChinaBorder *_china;
    QSpecialDistrictBorder *_specialDistrict;
}

+ (id)instance;
@property(retain, nonatomic) QSpecialDistrictBorder *specialDistrict; // @synthesize specialDistrict=_specialDistrict;
@property(retain, nonatomic) QChinaBorder *china; // @synthesize china=_china;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) int version; // @synthesize version=_version;
- (void).cxx_destruct;
- (_Bool)updateData:(id)arg1 version:(int)arg2;
- (void)downloadNewData:(id)arg1;
- (id)readLocalBorderData;
- (void)dealloc;
- (id)init;
- (_Bool)chinaContainsCoordinate:(struct CLLocationCoordinate2D)arg1;
- (int)queryCoordinate:(struct CLLocationCoordinate2D)arg1 andRect:(CDStruct_02837cd9)arg2;
- (_Bool)shouldCorrectCoordinateToGCJ02:(struct CLLocationCoordinate2D)arg1;

@end

