//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface QIndoorLocation : NSObject
{
    NSString *_buildUid;
    NSString *_levelName;
}

@property(copy, nonatomic) NSString *levelName; // @synthesize levelName=_levelName;
@property(copy, nonatomic) NSString *buildUid; // @synthesize buildUid=_buildUid;
- (void).cxx_destruct;

@end

