//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QOverlayContainer;
@protocol QOverlay;

@interface QOverlayView : UIView
{
    int _strokeId;
    int _fillId;
    id <QOverlay> _overlay;
    QOverlayContainer *_container;
}

@property(nonatomic) int fillId; // @synthesize fillId=_fillId;
@property(nonatomic) int strokeId; // @synthesize strokeId=_strokeId;
@property(nonatomic) __weak QOverlayContainer *container; // @synthesize container=_container;
@property(retain, nonatomic) id <QOverlay> overlay; // @synthesize overlay=_overlay;
- (void).cxx_destruct;
- (void)prepareForUse;

@end

