//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface QTileOverlay : NSObject
{
    _Bool _isHighResoultionTile;
    long long _priority;
}

@property(nonatomic) _Bool isHighResoultionTile; // @synthesize isHighResoultionTile=_isHighResoultionTile;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
- (id)initWithPriority:(long long)arg1;
- (id)init;
- (void)saveTileData:(id)arg1 atPath:(CDStruct_cf57a58b)arg2;
- (id)loadTileImageAtPath:(CDStruct_cf57a58b)arg1;
- (id)URLForTilePath:(CDStruct_cf57a58b)arg1;

@end

