//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;

@interface TBRepeatTimer : NSObject
{
    _Bool _addedInToRunloop;
    NSTimer *_timer;
    double _timeInterval;
    long long _repeatCount;
    CDUnknownBlockType _block;
    long long _firedCount;
}

@property(nonatomic) long long firedCount; // @synthesize firedCount=_firedCount;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) long long repeatCount; // @synthesize repeatCount=_repeatCount;
@property(nonatomic) double timeInterval; // @synthesize timeInterval=_timeInterval;
@property(nonatomic) _Bool addedInToRunloop; // @synthesize addedInToRunloop=_addedInToRunloop;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (id)initWithTimeInterval:(double)arg1 repeatCount:(long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)setupTimer;
- (void)run;
- (void)invalidate;
- (void)handleTimerFire;

@end

