//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BrandTimelineBaseCellView.h"

#import "BTLBaseItemViewDelegate-Protocol.h"
#import "BTLShowMoreItemViewDelegate-Protocol.h"

@class BTLShowMoreItemView, BrandTimelineMultiReaderViewModel, BrandTimelineSplitView, NSMutableArray, NSString;

@interface BrandTimelineMultiReaderCellView : BrandTimelineBaseCellView <BTLBaseItemViewDelegate, BTLShowMoreItemViewDelegate>
{
    unsigned int _selectIndex;
    NSMutableArray *_arrItemViews;
    BTLShowMoreItemView *_showMoreItemView;
    BrandTimelineSplitView *_splitView;
}

@property(retain, nonatomic) BrandTimelineSplitView *splitView; // @synthesize splitView=_splitView;
@property(nonatomic) unsigned int selectIndex; // @synthesize selectIndex=_selectIndex;
@property(retain, nonatomic) BTLShowMoreItemView *showMoreItemView; // @synthesize showMoreItemView=_showMoreItemView;
@property(retain, nonatomic) NSMutableArray *arrItemViews; // @synthesize arrItemViews=_arrItemViews;
- (void).cxx_destruct;
- (void)onDebug:(id)arg1;
- (void)onFavorite:(id)arg1;
- (void)onForward:(id)arg1;
- (void)handleMenuControllerWillHideMenuNotification:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)onBrandItemImageClick:(id)arg1 imageView:(id)arg2;
- (void)onBrandItemLongPress:(id)arg1;
- (void)onBrandItemTouchDown:(id)arg1;
- (void)onBrandItemClick:(id)arg1;
- (void)onReloadItemView:(id)arg1;
- (void)onShowMoreItemViewClick:(id)arg1;
- (void)layoutSubviews;
- (void)initSplitViewIfNeed;
- (void)initShowMoreViewIfNeed;
- (void)removeAllItemViews;
- (void)initItemViews;
- (void)updateViewModel:(id)arg1;
- (id)initWithModel:(id)arg1;
- (id)cellIdentifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) BrandTimelineMultiReaderViewModel *viewModel; // @dynamic viewModel;

@end

