//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CMessageWrap, NSString;

@protocol BrandTimelineMsgMgrExt

@optional
- (void)onAddNewSingleMsg:(CMessageWrap *)arg1;
- (void)onSingleUnreadMsgCountChange;
- (void)onClearAllTimelineMsgUnreadStatus;
- (void)onDelBrandTimelineMsg:(NSString *)arg1 msgWrap:(CMessageWrap *)arg2;
- (void)onDelBrandTimelineMsgBySession:(NSString *)arg1;
- (void)onModBrandTimelineMsg:(CMessageWrap *)arg1;
- (void)onAddBrandTimelineMsg:(CMessageWrap *)arg1;
- (void)onMigrateBrandMsgFinish:(unsigned long long)arg1;
@end

