//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BTLBaseItemView.h"

@class MMUIButton;

@interface BTLTextItemView : BTLBaseItemView
{
    MMUIButton *m_fullTextBtn;
}

- (void).cxx_destruct;
- (void)onFullTextBtnClick;
- (void)layoutTextItemTop;
- (void)layoutSubviews;
- (void)initFullTextBtn;
- (void)initTextItemTop;
- (id)initWithViewModel:(id)arg1;

@end

