//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QTileOverlay.h"

@class QQuadTree;

@interface QHeatTileOverlay : QTileOverlay
{
    float *_scaleMatrix;
    long long _decayRadius;
    double _max;
    double _zoomedOutMax;
    QQuadTree *_quadTree;
}

@property(retain, nonatomic) QQuadTree *quadTree; // @synthesize quadTree=_quadTree;
@property(nonatomic) double zoomedOutMax; // @synthesize zoomedOutMax=_zoomedOutMax;
@property(nonatomic) double max; // @synthesize max=_max;
@property(nonatomic) long long decayRadius; // @synthesize decayRadius=_decayRadius;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithHeatTileNodes:(id)arg1;
- (id)initWithHeatTileNodes:(id)arg1 decayRadius:(long long)arg2;
- (void)setupDecayRadius:(long long)arg1;
- (void)setupDecayMatrix;
- (void)setupQuadTreeWithHeatTileNodes:(id)arg1;
- (void)updateHeatTileNodes:(id)arg1;
- (id)loadTileImageAtPath:(CDStruct_cf57a58b)arg1;
- (id)heatNodesInRect:(struct CGRect)arg1 atScale:(double)arg2;
- (id)imageForNodes:(id)arg1 relativePoint:(struct CGPoint)arg2 zoom:(long long)arg3;
- (struct CGPoint)pointForNode:(id)arg1 relativePoint:(struct CGPoint)arg2 zoom:(long long)arg3;
- (void)testcolorForValue:(double)arg1 outRed:(double *)arg2 outGreen:(double *)arg3 outBlue:(double *)arg4 outAlpha:(double *)arg5;
- (void)colorForValue:(double)arg1 outRed:(double *)arg2 outGreen:(double *)arg3 outBlue:(double *)arg4 outAlpha:(double *)arg5;
- (id)loadingImageForPath:(CDStruct_cf57a58b)arg1;

@end

