//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QIndoorPickerDelegate-Protocol.h"
#import "QMapContextDelegate-Protocol.h"

@class NSString, QIndoorBuilding, QIndoorLevel, QIndoorPicker, QMapContext, UIView;
@protocol QIndoorManagerDelegate;

@interface QIndoorManager : NSObject <QMapContextDelegate, QIndoorPickerDelegate>
{
    _Bool _indoorPickerEnabled;
    QMapContext *_mapContext;
    UIView *_hostView;
    id <QIndoorManagerDelegate> _delegate;
    QIndoorBuilding *_activeBuilding;
    QIndoorPicker *_picker;
    unsigned long long _activeLevelIndex;
    struct CGPoint _indoorPickerOffset;
}

@property(nonatomic) unsigned long long activeLevelIndex; // @synthesize activeLevelIndex=_activeLevelIndex;
@property(retain, nonatomic) QIndoorPicker *picker; // @synthesize picker=_picker;
@property(retain, nonatomic) QIndoorBuilding *activeBuilding; // @synthesize activeBuilding=_activeBuilding;
@property(nonatomic) struct CGPoint indoorPickerOffset; // @synthesize indoorPickerOffset=_indoorPickerOffset;
@property(nonatomic) _Bool indoorPickerEnabled; // @synthesize indoorPickerEnabled=_indoorPickerEnabled;
@property(nonatomic) __weak id <QIndoorManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIView *hostView; // @synthesize hostView=_hostView;
@property(nonatomic) __weak QMapContext *mapContext; // @synthesize mapContext=_mapContext;
- (void).cxx_destruct;
- (void)setActiveIndoorLocation:(id)arg1;
@property(retain, nonatomic) QIndoorLevel *activeLevel;
@property(nonatomic, getter=isIndoorEnabled) _Bool indoorEnabled;
- (void)mapContext:(id)arg1 didChangeActiveBuilding:(id)arg2;
- (void)indoorPicker:(id)arg1 didSelectLevelIndex:(unsigned long long)arg2;
- (void)updateUI;
- (_Bool)IsIndoorValid;
- (void)callDelegateDidChangeActiveLevel:(id)arg1;
- (void)callDelegateDidChangeActiveBuilding:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

