//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QOverlayPathView.h"

@class NSArray, QPolyline, UIColor;

@interface QPolylineView : QOverlayPathView
{
    long long _displayLevel;
    double _borderWidth;
    UIColor *_borderColor;
    NSArray *_lineDashPattern;
}

@property(copy, nonatomic) NSArray *lineDashPattern; // @synthesize lineDashPattern=_lineDashPattern;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) long long displayLevel; // @synthesize displayLevel=_displayLevel;
- (void).cxx_destruct;
- (void)setFillColor:(id)arg1;
- (void)setLineWidth:(double)arg1;
- (void)setStrokeColor:(id)arg1;
@property(readonly, nonatomic) QPolyline *polyline;
- (id)initWithPolyline:(id)arg1;

@end

