//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QPolylineView.h"

@class NSArray, UIImage;

@interface QTexturePolylineView : QPolylineView
{
    _Bool _drawSymbol;
    NSArray *_segmentStyle;
    long long _drawType;
    UIImage *_styleTextureImage;
    double _footprintStep;
    UIImage *_symbolImage;
    double _symbolGap;
}

@property(nonatomic) double symbolGap; // @synthesize symbolGap=_symbolGap;
@property(retain, nonatomic) UIImage *symbolImage; // @synthesize symbolImage=_symbolImage;
@property(nonatomic, getter=isDrawSymbol) _Bool drawSymbol; // @synthesize drawSymbol=_drawSymbol;
@property(nonatomic) double footprintStep; // @synthesize footprintStep=_footprintStep;
@property(retain, nonatomic) UIImage *styleTextureImage; // @synthesize styleTextureImage=_styleTextureImage;
@property(nonatomic) long long drawType; // @synthesize drawType=_drawType;
@property(copy, nonatomic) NSArray *segmentStyle; // @synthesize segmentStyle=_segmentStyle;
- (void).cxx_destruct;
- (void)eraseFromStartToCurrentPoint:(struct CLLocationCoordinate2D)arg1 searchFrom:(int)arg2 toColor:(_Bool)arg3;
- (void)setBorderColor:(id)arg1;
- (void)setBorderWidth:(double)arg1;
- (void)setLineDashPattern:(id)arg1;
- (void)setFillColor:(id)arg1;
- (void)setStrokeColor:(id)arg1;
- (void)setLineWidth:(double)arg1;
- (id)initWithPolyline:(id)arg1;

@end

