//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QTileOverlay.h"

@class QWorldTileOverlayDataProvider;

@interface QWorldTileOverlay : QTileOverlay
{
    _Bool _specialWorldmap;
    int _language;
    QWorldTileOverlayDataProvider *_provider;
}

@property(retain, nonatomic) QWorldTileOverlayDataProvider *provider; // @synthesize provider=_provider;
@property(nonatomic) int language; // @synthesize language=_language;
@property(nonatomic) _Bool specialWorldmap; // @synthesize specialWorldmap=_specialWorldmap;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)onWorldVesionCheck:(id)arg1;
- (void)saveTileData:(id)arg1 atPath:(CDStruct_cf57a58b)arg2;
- (id)loadTileImageAtPath:(CDStruct_cf57a58b)arg1;
- (id)URLForTilePath:(CDStruct_cf57a58b)arg1;
- (_Bool)specialIsTaiwan;

@end

