//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;
@protocol TBRegionChangeDistributorDelegate;

@interface TBRegionChangeDistributor : NSObject
{
    _Bool _animated;
    _Bool _byGestured;
    id <TBRegionChangeDistributorDelegate> _delegate;
    NSOperationQueue *_queue;
    long long _zoomCount;
    long long _centerCount;
    long long _rotationCount;
    long long _overlookingCount;
}

@property(nonatomic) long long overlookingCount; // @synthesize overlookingCount=_overlookingCount;
@property(nonatomic) long long rotationCount; // @synthesize rotationCount=_rotationCount;
@property(nonatomic) long long centerCount; // @synthesize centerCount=_centerCount;
@property(nonatomic) long long zoomCount; // @synthesize zoomCount=_zoomCount;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(nonatomic) _Bool byGestured; // @synthesize byGestured=_byGestured;
@property(nonatomic) _Bool animated; // @synthesize animated=_animated;
@property(nonatomic) __weak id <TBRegionChangeDistributorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (void)reset;
- (void)completeOption:(unsigned long long)arg1;
- (void)registerOption:(unsigned long long)arg1 animated:(_Bool)arg2 byGesture:(_Bool)arg3;
- (void)notifyRegionDidChangeAnimated:(_Bool)arg1 byGesture:(_Bool)arg2;
- (void)notifyRegionWillChangeAnimated:(_Bool)arg1 byGesture:(_Bool)arg2;
- (_Bool)matchCompleted;

@end

