//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface WCAdStarRatingInfo : NSObject <NSCoding>
{
    double _actualScore;
    NSString *_fillColor;
}

@property(retain, nonatomic) NSString *fillColor; // @synthesize fillColor=_fillColor;
@property(nonatomic) double actualScore; // @synthesize actualScore=_actualScore;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

