//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface WCTimeLineStarRatingView : UIView
{
    double _actualScore;
    UIColor *_defaultColor;
    UIColor *_fillColor;
    double _innerMargin;
    double _totalScore;
}

@property(nonatomic) double totalScore; // @synthesize totalScore=_totalScore;
@property(nonatomic) double innerMargin; // @synthesize innerMargin=_innerMargin;
@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(retain, nonatomic) UIColor *defaultColor; // @synthesize defaultColor=_defaultColor;
@property(nonatomic) double actualScore; // @synthesize actualScore=_actualScore;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

