//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "BrandArticleSearchControllerDelegate-Protocol.h"
#import "BrandNewSingleMsgTipsCellViewDelegate-Protocol.h"
#import "BrandTimelineBaseCellViewDelegate-Protocol.h"
#import "BrandTimelineMsgMgrExt-Protocol.h"
#import "CAAnimationDelegate-Protocol.h"
#import "MMRefreshTableFooterDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "tableViewDelegate-Protocol.h"

@class BrandArticleSearchController, BrandNewSingleMsgTipsCellView, MMTableView, NSMutableArray, NSString, UIButton, UIView, WCTimeLineFooterView;

@interface BrandTimelineViewController : MMUIViewController <BrandArticleSearchControllerDelegate, BrandTimelineBaseCellViewDelegate, MMRefreshTableFooterDelegate, CAAnimationDelegate, BrandTimelineMsgMgrExt, BrandNewSingleMsgTipsCellViewDelegate, UITableViewDelegate, UITableViewDataSource, tableViewDelegate>
{
    BrandArticleSearchController *m_articleSearchController;
    UIView *m_searchBarMaskView;
    struct CGPoint m_topContentOffset;
    WCTimeLineFooterView *m_footerView;
    MMTableView *m_tableView;
    UIView *m_topNavView;
    UIButton *m_navNewTipsBtn;
    UIView *m_navDefaultTitleView;
    NSMutableArray *m_arrBrandViewModel;
    _Bool m_bLoadingData;
    BrandNewSingleMsgTipsCellView *m_newSingleMsgTipsCellView;
    unsigned int m_unreadSingleMsgCount;
    unsigned int m_topNavNewMsgCount;
    unsigned long long m_topLastNewMsgSequenceId;
    unsigned long long m_newMsgDividingLineSequenceId;
    NSString *_leftBarStr;
    unsigned long long _showType;
}

@property(nonatomic) unsigned long long showType; // @synthesize showType=_showType;
@property(retain, nonatomic) NSString *leftBarStr; // @synthesize leftBarStr=_leftBarStr;
- (void).cxx_destruct;
- (void)brandArticleSearchWillEndSearch;
- (void)brandArticleSearchWillBeginSearch;
- (void)onMigrateBrandMsgFinish:(unsigned long long)arg1;
- (void)onSingleUnreadMsgCountChange;
- (void)onDelBrandTimelineMsg:(id)arg1 msgWrap:(id)arg2;
- (void)onDelBrandTimelineMsgBySession:(id)arg1;
- (void)onClearAllTimelineMsgUnreadStatus;
- (void)onModBrandTimelineMsg:(id)arg1;
- (void)onAddBrandTimelineMsg:(id)arg1;
- (void)onBrandNewSingleMsgTipsCellViewClick;
- (void)onLongPressForDebug:(id)arg1;
- (void)onCellViewClickedExpan:(id)arg1;
- (void)onPreviewMsgImg:(id)arg1 originFrame:(struct CGRect)arg2 fromView:(id)arg3;
- (void)reloadCellWithCellView:(id)arg1;
- (void)onDeleteBrandContact:(id)arg1;
- (id)getViewController;
- (void)ayncNotifyEnterChat:(id)arg1;
- (void)tryLoadDownMoreMessage;
- (_Bool)shouldDownMoreLoading;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)viewControllerForBrandArticleSearch;
- (void)onNavBackBarButtonClicked;
- (void)showMessageList;
- (void)onScrollToTop;
- (void)onClickNavNewTipsBtn;
- (void)viewWillLayoutSubviews;
- (void)updateNewMsgDividingLinePosition;
- (void)updateVisibleCellTime;
- (void)initSearchBar;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;
- (void)updateNavigationBarWithNewMsgCount:(unsigned int)arg1;
- (void)initNavigationBar;
- (void)initFooterView;
- (void)updateLoadingState;
- (void)initTableView;
- (void)initData;
- (void)initView;
- (void)willEnterForeground:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewWillBePushed:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

