//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CALayer, NSMutableArray, RichTextView, UIImageView;
@protocol BTLShowMoreItemViewDelegate;

@interface BTLShowMoreItemView : UIButton
{
    NSMutableArray *m_labelStyles;
    RichTextView *m_tipsLabel;
    UIImageView *m_dropDownIcon;
    CALayer *m_separateLayer;
    id <BTLShowMoreItemViewDelegate> _delegate;
}

@property(nonatomic) __weak id <BTLShowMoreItemViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onClick;
- (void)layoutSubviews;
- (void)updateLabelStyles:(id)arg1;
- (void)initWithlabelStyles:(id)arg1;
- (id)initLabelStyles:(id)arg1;

@end

