//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BTLBaseItemViewModel.h"

#import "BrandTimelineMsgMgrExt-Protocol.h"

@class NSMutableArray, NSString;

@interface BTLVideoItemViewModel : BTLBaseItemViewModel <BrandTimelineMsgMgrExt>
{
    double m_viewHeight;
    NSMutableArray *m_titleLabelStyles;
    struct CGSize m_titleSize;
    NSString *_timeStr;
    NSString *_videoUrl;
}

+ (_Bool)canCreateViewModelWithReaderWrap:(id)arg1 msgWrap:(id)arg2;
@property(retain, nonatomic) NSString *videoUrl; // @synthesize videoUrl=_videoUrl;
@property(retain, nonatomic) NSString *timeStr; // @synthesize timeStr=_timeStr;
- (void).cxx_destruct;
- (void)onGetVideoUrlSuccess:(id)arg1 MsgUrl:(id)arg2;
- (void)onGetVideoUrlFail:(id)arg1;
- (struct CGSize)titleSize;
- (id)titleLabelStyles;
- (double)viewHeight;
- (id)itemViewClassName;
- (void)dealloc;
- (id)initWithReaderWrap:(id)arg1 itemIndex:(unsigned int)arg2 msgWrap:(id)arg3 contact:(id)arg4;

@end

