//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface QGlobaleDefines : NSObject
{
    _Bool _isAppKeyOK;
    _Bool _worldmapPrevilege;
    NSString *_cacheRootPath;
}

+ (long long)clientType;
+ (id)singleton;
@property(retain, nonatomic) NSString *cacheRootPath; // @synthesize cacheRootPath=_cacheRootPath;
@property(nonatomic) _Bool worldmapPrevilege; // @synthesize worldmapPrevilege=_worldmapPrevilege;
@property(nonatomic) _Bool isAppKeyOK; // @synthesize isAppKeyOK=_isAppKeyOK;
- (void).cxx_destruct;
- (id)imageNamed:(id)arg1;
- (void)updateHandDrawMapVersion:(id)arg1;
- (id)handDrawMapVersion;
- (void)updateOtherLogoVersion:(id)arg1;
- (id)otherLogoVersion;
- (void)updateWorldLogoVersion:(id)arg1;
- (id)worldLogoVersion;
- (void)updateLocalWorldVersionInfo:(id)arg1;
- (id)localWorldVersionInfo;
- (id)appendCommonUrlStatisticParamatersFor:(id)arg1;
- (id)constructURLStringWithArguments:(id)arg1 forUrl:(id)arg2;
- (id)percentString:(id)arg1;
- (id)constructCommonArguments;
- (id)appIdentifier;
- (id)DPI;
- (id)netType;
- (id)appVersion;
- (id)sdkVersion;
- (id)init;

@end

