//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class QMapContext, QTileDataDownloader;
@protocol QMapDataDelegate;

@interface QMapDataManager : NSObject
{
    QMapContext *_mapContext;
    id <QMapDataDelegate> _delegate;
    QTileDataDownloader *_tileDownloader;
}

@property(retain, nonatomic) QTileDataDownloader *tileDownloader; // @synthesize tileDownloader=_tileDownloader;
@property(nonatomic) __weak id <QMapDataDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak QMapContext *mapContext; // @synthesize mapContext=_mapContext;
- (void).cxx_destruct;
- (void)notifyDidFailLoadingWithError:(id)arg1;
- (void)downloadTileWithUrl:(id)arg1;
- (id)init;

@end

