//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class QMapContext, QMediator, TBOrderedSafeDictionary;

@interface QOverlayContainer : NSObject
{
    QMediator *_mediator;
    QMapContext *_mapContext;
    TBOrderedSafeDictionary *_viewContainer;
}

@property(retain, nonatomic) TBOrderedSafeDictionary *viewContainer; // @synthesize viewContainer=_viewContainer;
@property(nonatomic) __weak QMapContext *mapContext; // @synthesize mapContext=_mapContext;
@property(nonatomic) __weak QMediator *mediator; // @synthesize mediator=_mediator;
- (void).cxx_destruct;
- (void)circleMapPoints:(CDStruct_c3b9c2ee)arg1 radius:(double)arg2 mapPoints:(CDStruct_c3b9c2ee *)arg3 mapPointsCount:(int)arg4;
- (void)setNeedsDisplay;
- (id)handlerForOverlayView:(id)arg1;
- (id)payloadForCircle:(id)arg1 generatePoints:(_Bool)arg2;
- (id)payloadForPolygon:(id)arg1;
- (id)payloadForPolyline:(id)arg1;
- (void)updateCircleRadius:(id)arg1;
- (void)updateCircleViewFillStyle:(id)arg1;
- (void)updateCircleViewStrokeStyle:(id)arg1;
- (void)updatePolygonViewFillStyle:(id)arg1;
- (void)updatePolygonViewStrokeStyle:(id)arg1;
- (void)updatePolylineView:(id)arg1 changeStyleFromStartToCurrentPoint:(struct CLLocationCoordinate2D)arg2 searchFrom:(int)arg3 toColor:(_Bool)arg4;
- (void)updatePolylineView:(id)arg1 RGBAColorStyles:(_Bool)arg2;
- (void)updatePolylineView:(id)arg1 segStyles:(_Bool)arg2;
- (id)overlays;
- (id)viewForOverlay:(id)arg1;
- (void)removeOverlayView:(id)arg1;
- (void)addOverlayView:(id)arg1;
- (id)init;

@end

