//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface QPathViewPayload : NSObject
{
    float _lineWidth;
    int _pointCount;
    float _circleRadiusScale;
    UIColor *_strokeColor;
    UIColor *_fillColor;
    CDStruct_c3b9c2ee *_points;
    CDStruct_34734122 _originPoint;
}

@property(nonatomic) float circleRadiusScale; // @synthesize circleRadiusScale=_circleRadiusScale;
@property(nonatomic) int pointCount; // @synthesize pointCount=_pointCount;
@property(nonatomic) CDStruct_c3b9c2ee *points; // @synthesize points=_points;
@property(nonatomic) CDStruct_c3b9c2ee originPoint; // @synthesize originPoint=_originPoint;
@property(nonatomic) float lineWidth; // @synthesize lineWidth=_lineWidth;
@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

