//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSSet, QMapContext, QMediator, QRoadEventDownloader, TBRepeatTimer;
@protocol OS_dispatch_queue;

@interface QRoadEventManager : NSObject
{
    QMapContext *_mapContext;
    QMediator *_mediator;
    NSSet *_citiList;
    double _prevTime;
    QRoadEventDownloader *_downloader;
    TBRepeatTimer *_timer;
    NSMutableDictionary *_city2version;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *city2version; // @synthesize city2version=_city2version;
@property(retain, nonatomic) TBRepeatTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) QRoadEventDownloader *downloader; // @synthesize downloader=_downloader;
@property(nonatomic) double prevTime; // @synthesize prevTime=_prevTime;
@property(retain) NSSet *citiList; // @synthesize citiList=_citiList;
@property(nonatomic) __weak QMediator *mediator; // @synthesize mediator=_mediator;
@property(nonatomic) __weak QMapContext *mapContext; // @synthesize mapContext=_mapContext;
- (void).cxx_destruct;
- (_Bool)saveCity:(id)arg1 data:(id)arg2;
- (void)removeCity:(id)arg1;
- (id)fileNameForCity:(id)arg1;
- (id)savePath;
- (void)reloadCitiesData:(id)arg1;
- (void)doRefreshRoadData:(id)arg1;
- (void)refreshRoadData:(double)arg1;
- (void)autoRefreh;
- (void)resetTimer;
- (void)setRoadEventEnable:(_Bool)arg1;
- (void)dealloc;
- (id)init;

@end

