//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, QDataCacheWorldmapStandard;

@interface QWorldTileOverlayDataProvider : NSObject
{
    _Bool _isSpecialmap;
    NSString *_styleId;
    NSString *_scene;
    NSString *_version;
    NSString *_sourceType;
    NSString *_urlTemplate;
    QDataCacheWorldmapStandard *_dataCache;
    NSArray *_langCandidates;
}

@property(retain, nonatomic) NSArray *langCandidates; // @synthesize langCandidates=_langCandidates;
@property(retain, nonatomic) QDataCacheWorldmapStandard *dataCache; // @synthesize dataCache=_dataCache;
@property(copy, nonatomic) NSString *urlTemplate; // @synthesize urlTemplate=_urlTemplate;
@property(copy, nonatomic) NSString *sourceType; // @synthesize sourceType=_sourceType;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *scene; // @synthesize scene=_scene;
@property(copy, nonatomic) NSString *styleId; // @synthesize styleId=_styleId;
@property(nonatomic) _Bool isSpecialmap; // @synthesize isSpecialmap=_isSpecialmap;
- (void).cxx_destruct;
- (id)generateUrl:(id)arg1;
- (void)resetData;
- (int)tileType;
- (CDStruct_43274f37)tileForPath:(CDStruct_cf57a58b)arg1;
- (void)saveTileData:(id)arg1 atPath:(CDStruct_cf57a58b)arg2;
- (id)loadTileImageAtPath:(CDStruct_cf57a58b)arg1;
- (id)URLForTilePath:(CDStruct_cf57a58b)arg1;
- (id)languageString:(int)arg1;
- (_Bool)specialIsTaiwan;
- (id)init;

@end

